"""empty message

Revision ID: 25442959da8b
Revises: 
Create Date: 2021-08-30 11:55:29.259089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25442959da8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectName', sa.String(length=50), nullable=True),
    sa.Column('projectDescription', sa.String(length=300), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectName')
    )
    op.create_table('apiTest_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('e_name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('e_description', sa.String(length=300), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apiTest_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('apiTestcase_id', sa.Integer(), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('api_name', sa.String(length=100), nullable=True),
    sa.Column('output_log', sa.LargeBinary(length=300), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['apiTest_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectEnvironment_id', sa.Integer(), nullable=True),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('module_description', sa.String(length=300), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projectEnvironment_id'], ['project_environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['e_id'], ['project_environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apiModule_id', sa.Integer(), nullable=True),
    sa.Column('api_name', sa.String(length=100), nullable=True),
    sa.Column('request_method', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=50), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(create_constraint=10), nullable=True),
    sa.Column('independent', sa.Boolean(create_constraint=10), nullable=True),
    sa.ForeignKeyConstraint(['apiModule_id'], ['api_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_testcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_header', sa.String(length=3000), nullable=True),
    sa.Column('request_body', sa.String(length=3000), nullable=True),
    sa.Column('request_param', sa.String(length=3000), nullable=True),
    sa.Column('encode', sa.String(length=50), nullable=True),
    sa.Column('verify', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_assert', sa.String(length=10), nullable=True),
    sa.Column('assert_content', sa.String(length=3000), nullable=True),
    sa.Column('is_post_processor', sa.String(length=10), nullable=True),
    sa.Column('post_processor_content', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_testcase')
    op.drop_table('api')
    op.drop_table('environment_variable')
    op.drop_table('api_module')
    op.drop_table('apiTest_detail')
    op.drop_table('project_environment')
    op.drop_table('apiTest_task')
    op.drop_table('project')
    # ### end Alembic commands ###
