"""empty message

Revision ID: 5db5a539a2d7
Revises: ba5636f1628d
Create Date: 2022-07-01 10:53:53.874631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5db5a539a2d7'
down_revision = 'ba5636f1628d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('apiTest_task',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('project_id', sa.Integer(), nullable=True),
    # sa.Column('title', sa.String(length=50), nullable=True),
    # sa.Column('summary', sa.String(length=200), nullable=True),
    # sa.Column('create_time', sa.DateTime(), nullable=True),
    # sa.Column('status', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_push', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('apiTest_detail',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('task_id', sa.Integer(), nullable=True),
    # sa.Column('apiTestcase_id', sa.Integer(), nullable=True),
    # sa.Column('module_name', sa.String(length=100), nullable=True),
    # sa.Column('api_name', sa.String(length=100), nullable=True),
    # sa.Column('testcase_name', sa.String(length=100), nullable=True),
    # sa.Column('output_log', sa.Text(), nullable=True),
    # sa.Column('create_time', sa.DateTime(), nullable=True),
    # sa.Column('status', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['task_id'], ['apiTest_task.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('apitest_detail')
    # op.drop_table('apitest_task')
    # op.drop_constraint('api_ibfk_1', 'api', type_='foreignkey')
    # op.create_foreign_key(None, 'api', 'project_module', ['apiModule_id'], ['id'])
    # op.drop_column('api_testcase', 'request_param')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_testcase', sa.Column('request_param', mysql.VARCHAR(length=3000), nullable=True))
    op.drop_constraint(None, 'api', type_='foreignkey')
    op.create_foreign_key('api_ibfk_1', 'api', 'project_module', ['apiModule_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_table('apitest_task',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('summary', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='apitest_task_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('apitest_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apiTestcase_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('api_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testcase_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('output_log', mysql.TEXT(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['apitest_task.id'], name='apitest_detail_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('apiTest_detail')
    op.drop_table('message')
    op.drop_table('apiTest_task')
    # ### end Alembic commands ###
