"""empty message

Revision ID: ec2a6467e080
Revises: 
Create Date: 2022-02-16 10:46:13.769652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec2a6467e080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_module')
    op.drop_table('project_environment')
    op.drop_table('apitest_task')
    op.drop_table('user')
    op.drop_table('submitted_tests')
    op.drop_index('projectName', table_name='project')
    op.drop_table('project')
    op.drop_table('api')
    op.drop_table('data_dictionary')
    op.drop_table('environment_variable')
    op.drop_table('api_testcase')
    op.drop_table('apitest_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apitest_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apiTestcase_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('api_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testcase_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('output_log', mysql.TEXT(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['apitest_task.id'], name='apitest_detail_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('api_testcase',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('request_header', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('request_body', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('encode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('verify', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('request_param', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('assert_content', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_assert', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('request_method', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('is_post_processor', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('post_processor_content', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], name='api_testcase_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('environment_variable',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('e_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('value', mysql.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['e_id'], ['project_environment.id'], name='environment_variable_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('data_dictionary',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('value', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('api',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('apiModule_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_method', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('summary', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('seq', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('independent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('api_name', mysql.VARCHAR(length=100), nullable=True),
    sa.CheckConstraint('(`independent` in (0,1))', name='api_chk_1'),
    sa.ForeignKeyConstraint(['apiModule_id'], ['api_module.id'], name='api_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('project',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('projectDescription', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('projectName', 'project', ['projectName'], unique=True)
    op.create_table('submitted_tests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_test_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('submitted_test_detail', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('submitted_date', mysql.DATETIME(), nullable=True),
    sa.Column('submitted_test_director', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('test_director', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('test_status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('smoke_testing_result', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('smoke_testing_fail_reason_category', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('smoke_testing_fail_reason_detail', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('test_result', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('complete_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='submitted_tests_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('apitest_task',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('summary', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='apitest_task_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('project_environment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('e_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('e_description', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_environment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('api_module',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectEnvironment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('module_description', mysql.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['projectEnvironment_id'], ['project_environment.id'], name='api_module_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
